// LISTA COMPLETA DE 645 CIDADES DE SÃO PAULO
const CIDADES_BRASIL = [
  { nome: "Adamantina", uf: "SP" },
  { nome: "Adolfo", uf: "SP" },
  { nome: "Aguaí", uf: "SP" },
  { nome: "Águas da Prata", uf: "SP" },
  { nome: "Águas de Lindóia", uf: "SP" },
  { nome: "Águas de Santa Bárbara", uf: "SP" },
  { nome: "Águas de São Pedro", uf: "SP" },
  { nome: "Agudos", uf: "SP" },
  { nome: "Alambari", uf: "SP" },
  { nome: "Alfredo Marcondes", uf: "SP" },
  { nome: "Altair", uf: "SP" },
  { nome: "Altinópolis", uf: "SP" },
  { nome: "Alto Alegre", uf: "SP" },
  { nome: "Alumínio", uf: "SP" },
  { nome: "Álvares Florence", uf: "SP" },
  { nome: "Álvares Machado", uf: "SP" },
  { nome: "Álvaro de Carvalho", uf: "SP" },
  { nome: "Alvinlândia", uf: "SP" },
  { nome: "Americana", uf: "SP" },
  { nome: "Américo Brasiliense", uf: "SP" },
  { nome: "Américo de Campos", uf: "SP" },
  { nome: "Amparo", uf: "SP" },
  { nome: "Analândia", uf: "SP" },
  { nome: "Andradina", uf: "SP" },
  { nome: "Angatuba", uf: "SP" },
  { nome: "Anhembi", uf: "SP" },
  { nome: "Anhumas", uf: "SP" },
  { nome: "Aparecida", uf: "SP" },
  { nome: "Aparecida d'Oeste", uf: "SP" },
  { nome: "Apiaí", uf: "SP" },
  { nome: "Araçariguama", uf: "SP" },
  { nome: "Araçatuba", uf: "SP" },
  { nome: "Araçoiaba da Serra", uf: "SP" },
  { nome: "Aramina", uf: "SP" },
  { nome: "Arandu", uf: "SP" },
  { nome: "Arapeí", uf: "SP" },
  { nome: "Araraquara", uf: "SP" },
  { nome: "Araras", uf: "SP" },
  { nome: "Arco-Íris", uf: "SP" },
  { nome: "Arealva", uf: "SP" },
  { nome: "Areias", uf: "SP" },
  { nome: "Areiópolis", uf: "SP" },
  { nome: "Ariranha", uf: "SP" },
  { nome: "Artur Nogueira", uf: "SP" },
  { nome: "Arujá", uf: "SP" },
  { nome: "Aspásia", uf: "SP" },
  { nome: "Assis", uf: "SP" },
  { nome: "Atibaia", uf: "SP" },
  { nome: "Auriflama", uf: "SP" },
  { nome: "Avaí", uf: "SP" },
  { nome: "Avanhandava", uf: "SP" },
  { nome: "Avaré", uf: "SP" },
  { nome: "Bady Bassitt", uf: "SP" },
  { nome: "Balbinos", uf: "SP" },
  { nome: "Bálsamo", uf: "SP" },
  { nome: "Bananal", uf: "SP" },
  { nome: "Barão de Antonina", uf: "SP" },
  { nome: "Barbosa", uf: "SP" },
  { nome: "Bariri", uf: "SP" },
  { nome: "Barra Bonita", uf: "SP" },
  { nome: "Barra do Chapéu", uf: "SP" },
  { nome: "Barra do Turvo", uf: "SP" },
  { nome: "Barretos", uf: "SP" },
  { nome: "Barrinha", uf: "SP" },
  { nome: "Barueri", uf: "SP" },
  { nome: "Bastos", uf: "SP" },
  { nome: "Batatais", uf: "SP" },
  { nome: "Bauru", uf: "SP" },
  { nome: "Bebedouro", uf: "SP" },
  { nome: "Bento de Abreu", uf: "SP" },
  { nome: "Bernardino de Campos", uf: "SP" },
  { nome: "Bertioga", uf: "SP" },
  { nome: "Bilac", uf: "SP" },
  { nome: "Birigui", uf: "SP" },
  { nome: "Biritiba Mirim", uf: "SP" },
  { nome: "Boa Esperança do Sul", uf: "SP" },
  { nome: "Bocaina", uf: "SP" },
  { nome: "Bofete", uf: "SP" },
  { nome: "Boituva", uf: "SP" },
  { nome: "Bom Jesus dos Perdões", uf: "SP" },
  { nome: "Bom Sucesso de Itararé", uf: "SP" },
  { nome: "Borá", uf: "SP" },
  { nome: "Boracéia", uf: "SP" },
  { nome: "Borborema", uf: "SP" },
  { nome: "Borebi", uf: "SP" },
  { nome: "Botucatu", uf: "SP" },
  { nome: "Bragança Paulista", uf: "SP" },
  { nome: "Braúna", uf: "SP" },
  { nome: "Brejo Alegre", uf: "SP" },
  { nome: "Brodowski", uf: "SP" },
  { nome: "Brotas", uf: "SP" },
  { nome: "Buri", uf: "SP" },
  { nome: "Buritama", uf: "SP" },
  { nome: "Buritizal", uf: "SP" },
  { nome: "Cabrália Paulista", uf: "SP" },
  { nome: "Cabreúva", uf: "SP" },
  { nome: "Caçapava", uf: "SP" },
  { nome: "Cachoeira Paulista", uf: "SP" },
  { nome: "Caconde", uf: "SP" },
  { nome: "Cafelândia", uf: "SP" },
  { nome: "Caiabu", uf: "SP" },
  { nome: "Caieiras", uf: "SP" },
  { nome: "Caiuá", uf: "SP" },
  { nome: "Cajamar", uf: "SP" },
  { nome: "Cajati", uf: "SP" },
  { nome: "Cajobi", uf: "SP" },
  { nome: "Cajuru", uf: "SP" },
  { nome: "Campina do Monte Alegre", uf: "SP" },
  { nome: "Campinas", uf: "SP" },
  { nome: "Campo Limpo Paulista", uf: "SP" },
  { nome: "Campos do Jordão", uf: "SP" },
  { nome: "Campos Novos Paulista", uf: "SP" },
  { nome: "Cananéia", uf: "SP" },
  { nome: "Canas", uf: "SP" },
  { nome: "Cândido Mota", uf: "SP" },
  { nome: "Cândido Rodrigues", uf: "SP" },
  { nome: "Canitar", uf: "SP" },
  { nome: "Capão Bonito", uf: "SP" },
  { nome: "Capela do Alto", uf: "SP" },
  { nome: "Capivari", uf: "SP" },
  { nome: "Caraguatatuba", uf: "SP" },
  { nome: "Carapicuíba", uf: "SP" },
  { nome: "Cardoso", uf: "SP" },
  { nome: "Casa Branca", uf: "SP" },
  { nome: "Cássia dos Coqueiros", uf: "SP" },
  { nome: "Castilho", uf: "SP" },
  { nome: "Catanduva", uf: "SP" },
  { nome: "Catiguá", uf: "SP" },
  { nome: "Cedral", uf: "SP" },
  { nome: "Cerqueira César", uf: "SP" },
  { nome: "Cerquilho", uf: "SP" },
  { nome: "Cesário Lange", uf: "SP" },
  { nome: "Charqueada", uf: "SP" },
  { nome: "Clementina", uf: "SP" },
  { nome: "Colina", uf: "SP" },
  { nome: "Colômbia", uf: "SP" },
  { nome: "Conchal", uf: "SP" },
  { nome: "Conchas", uf: "SP" },
  { nome: "Cordeirópolis", uf: "SP" },
  { nome: "Coroados", uf: "SP" },
  { nome: "Coronel Macedo", uf: "SP" },
  { nome: "Corumbataí", uf: "SP" },
  { nome: "Cosmópolis", uf: "SP" },
  { nome: "Cosmorama", uf: "SP" },
  { nome: "Cotia", uf: "SP" },
  { nome: "Cravinhos", uf: "SP" },
  { nome: "Cristais Paulista", uf: "SP" },
  { nome: "Cruzália", uf: "SP" },
  { nome: "Cruzeiro", uf: "SP" },
  { nome: "Cubatão", uf: "SP" },
  { nome: "Cunha", uf: "SP" },
  { nome: "Descalvado", uf: "SP" },
  { nome: "Diadema", uf: "SP" },
  { nome: "Dirce Reis", uf: "SP" },
  { nome: "Divinolândia", uf: "SP" },
  { nome: "Dobrada", uf: "SP" },
  { nome: "Dois Córregos", uf: "SP" },
  { nome: "Dolcinópolis", uf: "SP" },
  { nome: "Dourado", uf: "SP" },
  { nome: "Dracena", uf: "SP" },
  { nome: "Duartina", uf: "SP" },
  { nome: "Dumont", uf: "SP" },
  { nome: "Echaporã", uf: "SP" },
  { nome: "Eldorado", uf: "SP" },
  { nome: "Elias Fausto", uf: "SP" },
  { nome: "Elisiário", uf: "SP" },
  { nome: "Embaúba", uf: "SP" },
  { nome: "Embu das Artes", uf: "SP" },
  { nome: "Embu-Guaçu", uf: "SP" },
  { nome: "Emilianópolis", uf: "SP" },
  { nome: "Engenheiro Coelho", uf: "SP" },
  { nome: "Espírito Santo do Pinhal", uf: "SP" },
  { nome: "Espírito Santo do Turvo", uf: "SP" },
  { nome: "Estrela d'Oeste", uf: "SP" },
  { nome: "Estrela do Norte", uf: "SP" },
  { nome: "Euclides da Cunha Paulista", uf: "SP" },
  { nome: "Fartura", uf: "SP" },
  { nome: "Fernandópolis", uf: "SP" },
  { nome: "Fernando Prestes", uf: "SP" },
  { nome: "Fernão", uf: "SP" },
  { nome: "Ferraz de Vasconcelos", uf: "SP" },
  { nome: "Flora Rica", uf: "SP" },
  { nome: "Floreal", uf: "SP" },
  { nome: "Flórida Paulista", uf: "SP" },
  { nome: "Florínea", uf: "SP" },
  { nome: "Franca", uf: "SP" },
  { nome: "Francisco Morato", uf: "SP" },
  { nome: "Franco da Rocha", uf: "SP" },
  { nome: "Gabriel Monteiro", uf: "SP" },
  { nome: "Gália", uf: "SP" },
  { nome: "Garça", uf: "SP" },
  { nome: "Gastão Vidigal", uf: "SP" },
  { nome: "Gavião Peixoto", uf: "SP" },
  { nome: "General Salgado", uf: "SP" },
  { nome: "Getulina", uf: "SP" },
  { nome: "Glicério", uf: "SP" },
  { nome: "Guaiçara", uf: "SP" },
  { nome: "Guaimbê", uf: "SP" },
  { nome: "Guaíra", uf: "SP" },
  { nome: "Guapiaçu", uf: "SP" },
  { nome: "Guapiara", uf: "SP" },
  { nome: "Guará", uf: "SP" },
  { nome: "Guaraçaí", uf: "SP" },
  { nome: "Guaraci", uf: "SP" },
  { nome: "Guarani d'Oeste", uf: "SP" },
  { nome: "Guarantã", uf: "SP" },
  { nome: "Guararapes", uf: "SP" },
  { nome: "Guararema", uf: "SP" },
  { nome: "Guaratinguetá", uf: "SP" },
  { nome: "Guareí", uf: "SP" },
  { nome: "Guariba", uf: "SP" },
  { nome: "Guarujá", uf: "SP" },
  { nome: "Guarulhos", uf: "SP" },
  { nome: "Guatapará", uf: "SP" },
  { nome: "Guzolândia", uf: "SP" },
  { nome: "Herculândia", uf: "SP" },
  { nome: "Holambra", uf: "SP" },
  { nome: "Hortolândia", uf: "SP" },
  { nome: "Iacanga", uf: "SP" },
  { nome: "Iacri", uf: "SP" },
  { nome: "Iaras", uf: "SP" },
  { nome: "Ibaté", uf: "SP" },
  { nome: "Ibirá", uf: "SP" },
  { nome: "Ibirarema", uf: "SP" },
  { nome: "Ibitinga", uf: "SP" },
  { nome: "Ibiúna", uf: "SP" },
  { nome: "Icém", uf: "SP" },
  { nome: "Iepê", uf: "SP" },
  { nome: "Igaraçu do Tietê", uf: "SP" },
  { nome: "Igarapava", uf: "SP" },
  { nome: "Igaratá", uf: "SP" },
  { nome: "Iguape", uf: "SP" },
  { nome: "Ilhabela", uf: "SP" },
  { nome: "Ilha Comprida", uf: "SP" },
  { nome: "Ilha Solteira", uf: "SP" },
  { nome: "Indaiatuba", uf: "SP" },
  { nome: "Indiana", uf: "SP" },
  { nome: "Indiaporã", uf: "SP" },
  { nome: "Inúbia Paulista", uf: "SP" },
  { nome: "Ipaussu", uf: "SP" },
  { nome: "Iperó", uf: "SP" },
  { nome: "Ipeúna", uf: "SP" },
  { nome: "Ipiguá", uf: "SP" },
  { nome: "Iporanga", uf: "SP" },
  { nome: "Ipuã", uf: "SP" },
  { nome: "Iracemápolis", uf: "SP" },
  { nome: "Irapuã", uf: "SP" },
  { nome: "Irapuru", uf: "SP" },
  { nome: "Itaberá", uf: "SP" },
  { nome: "Itaí", uf: "SP" },
  { nome: "Itajobi", uf: "SP" },
  { nome: "Itaju", uf: "SP" },
  { nome: "Itanhaém", uf: "SP" },
  { nome: "Itaoca", uf: "SP" },
  { nome: "Itapecerica da Serra", uf: "SP" },
  { nome: "Itapetininga", uf: "SP" },
  { nome: "Itapeva", uf: "SP" },
  { nome: "Itapevi", uf: "SP" },
  { nome: "Itapira", uf: "SP" },
  { nome: "Itapirapuã Paulista", uf: "SP" },
  { nome: "Itápolis", uf: "SP" },
  { nome: "Itaporanga", uf: "SP" },
  { nome: "Itapuí", uf: "SP" },
  { nome: "Itapura", uf: "SP" },
  { nome: "Itaquaquecetuba", uf: "SP" },
  { nome: "Itararé", uf: "SP" },
  { nome: "Itariri", uf: "SP" },
  { nome: "Itatiba", uf: "SP" },
  { nome: "Itatinga", uf: "SP" },
  { nome: "Itirapina", uf: "SP" },
  { nome: "Itirapuã", uf: "SP" },
  { nome: "Itobi", uf: "SP" },
  { nome: "Itu", uf: "SP" },
  { nome: "Itupeva", uf: "SP" },
  { nome: "Ituverava", uf: "SP" },
  { nome: "Jaborandi", uf: "SP" },
  { nome: "Jaboticabal", uf: "SP" },
  { nome: "Jacareí", uf: "SP" },
  { nome: "Jaci", uf: "SP" },
  { nome: "Jacupiranga", uf: "SP" },
  { nome: "Jaguariúna", uf: "SP" },
  { nome: "Jales", uf: "SP" },
  { nome: "Jambeiro", uf: "SP" },
  { nome: "Jandira", uf: "SP" },
  { nome: "Jardinópolis", uf: "SP" },
  { nome: "Jarinu", uf: "SP" },
  { nome: "Jaú", uf: "SP" },
  { nome: "Jeriquara", uf: "SP" },
  { nome: "Joanópolis", uf: "SP" },
  { nome: "João Ramalho", uf: "SP" },
  { nome: "José Bonifácio", uf: "SP" },
  { nome: "Júlio Mesquita", uf: "SP" },
  { nome: "Jumirim", uf: "SP" },
  { nome: "Jundiaí", uf: "SP" },
  { nome: "Junqueirópolis", uf: "SP" },
  { nome: "Juquiá", uf: "SP" },
  { nome: "Juquitiba", uf: "SP" },
  { nome: "Lagoinha", uf: "SP" },
  { nome: "Laranjal Paulista", uf: "SP" },
  { nome: "Lavínia", uf: "SP" },
  { nome: "Lavrinhas", uf: "SP" },
  { nome: "Leme", uf: "SP" },
  { nome: "Lençóis Paulista", uf: "SP" },
  { nome: "Limeira", uf: "SP" },
  { nome: "Lindóia", uf: "SP" },
  { nome: "Lins", uf: "SP" },
  { nome: "Lorena", uf: "SP" },
  { nome: "Lourdes", uf: "SP" },
  { nome: "Louveira", uf: "SP" },
  { nome: "Lucélia", uf: "SP" },
  { nome: "Lucianópolis", uf: "SP" },
  { nome: "Luís Antônio", uf: "SP" },
  { nome: "Luiziânia", uf: "SP" },
  { nome: "Lupércio", uf: "SP" },
  { nome: "Lutécia", uf: "SP" },
  { nome: "Macatuba", uf: "SP" },
  { nome: "Macaubal", uf: "SP" },
  { nome: "Macedônia", uf: "SP" },
  { nome: "Magda", uf: "SP" },
  { nome: "Mairinque", uf: "SP" },
  { nome: "Mairiporã", uf: "SP" },
  { nome: "Manduri", uf: "SP" },
  { nome: "Marabá Paulista", uf: "SP" },
  { nome: "Maracaí", uf: "SP" },
  { nome: "Marapoama", uf: "SP" },
  { nome: "Mariápolis", uf: "SP" },
  { nome: "Marília", uf: "SP" },
  { nome: "Marinópolis", uf: "SP" },
  { nome: "Martinópolis", uf: "SP" },
  { nome: "Matão", uf: "SP" },
  { nome: "Mauá", uf: "SP" },
  { nome: "Mendonça", uf: "SP" },
  { nome: "Meridiano", uf: "SP" },
  { nome: "Mesópolis", uf: "SP" },
  { nome: "Miguelópolis", uf: "SP" },
  { nome: "Mineiros do Tietê", uf: "SP" },
  { nome: "Miracatu", uf: "SP" },
  { nome: "Mira Estrela", uf: "SP" },
  { nome: "Mirandópolis", uf: "SP" },
  { nome: "Mirante do Paranapanema", uf: "SP" },
  { nome: "Mirassol", uf: "SP" },
  { nome: "Mirassolândia", uf: "SP" },
  { nome: "Mococa", uf: "SP" },
  { nome: "Mogi das Cruzes", uf: "SP" },
  { nome: "Mogi Guaçu", uf: "SP" },
  { nome: "Mogi Mirim", uf: "SP" },
  { nome: "Mombuca", uf: "SP" },
  { nome: "Monções", uf: "SP" },
  { nome: "Mongaguá", uf: "SP" },
  { nome: "Monte Alegre do Sul", uf: "SP" },
  { nome: "Monte Alto", uf: "SP" },
  { nome: "Monte Aprazível", uf: "SP" },
  { nome: "Monte Azul Paulista", uf: "SP" },
  { nome: "Monte Castelo", uf: "SP" },
  { nome: "Monteiro Lobato", uf: "SP" },
  { nome: "Monte Mor", uf: "SP" },
  { nome: "Morro Agudo", uf: "SP" },
  { nome: "Morungaba", uf: "SP" },
  { nome: "Motuca", uf: "SP" },
  { nome: "Murutinga do Sul", uf: "SP" },
  { nome: "Nantes", uf: "SP" },
  { nome: "Narandiba", uf: "SP" },
  { nome: "Natividade da Serra", uf: "SP" },
  { nome: "Nazaré Paulista", uf: "SP" },
  { nome: "Neves Paulista", uf: "SP" },
  { nome: "Nhandeara", uf: "SP" },
  { nome: "Nipoã", uf: "SP" },
  { nome: "Nova Aliança", uf: "SP" },
  { nome: "Nova Campina", uf: "SP" },
  { nome: "Nova Canaã Paulista", uf: "SP" },
  { nome: "Nova Castilho", uf: "SP" },
  { nome: "Nova Europa", uf: "SP" },
  { nome: "Nova Granada", uf: "SP" },
  { nome: "Nova Guataporanga", uf: "SP" },
  { nome: "Nova Independência", uf: "SP" },
  { nome: "Novais", uf: "SP" },
  { nome: "Nova Luzitânia", uf: "SP" },
  { nome: "Nova Odessa", uf: "SP" },
  { nome: "Novo Horizonte", uf: "SP" },
  { nome: "Nuporanga", uf: "SP" },
  { nome: "Ocauçu", uf: "SP" },
  { nome: "Óleo", uf: "SP" },
  { nome: "Olímpia", uf: "SP" },
  { nome: "Onda Verde", uf: "SP" },
  { nome: "Oriente", uf: "SP" },
  { nome: "Orindiúva", uf: "SP" },
  { nome: "Orlândia", uf: "SP" },
  { nome: "Osasco", uf: "SP" },
  { nome: "Oscar Bressane", uf: "SP" },
  { nome: "Osvaldo Cruz", uf: "SP" },
  { nome: "Ourinhos", uf: "SP" },
  { nome: "Ouroeste", uf: "SP" },
  { nome: "Ouro Verde", uf: "SP" },
  { nome: "Pacaembu", uf: "SP" },
  { nome: "Palestina", uf: "SP" },
  { nome: "Palmares Paulista", uf: "SP" },
  { nome: "Palmeira d'Oeste", uf: "SP" },
  { nome: "Palmital", uf: "SP" },
  { nome: "Panorama", uf: "SP" },
  { nome: "Paraguaçu Paulista", uf: "SP" },
  { nome: "Paraibuna", uf: "SP" },
  { nome: "Paraíso", uf: "SP" },
  { nome: "Paranapanema", uf: "SP" },
  { nome: "Paranapuã", uf: "SP" },
  { nome: "Parapuã", uf: "SP" },
  { nome: "Pardinho", uf: "SP" },
  { nome: "Pariquera-Açu", uf: "SP" },
  { nome: "Parisi", uf: "SP" },
  { nome: "Patrocínio Paulista", uf: "SP" },
  { nome: "Paulicéia", uf: "SP" },
  { nome: "Paulínia", uf: "SP" },
  { nome: "Paulistânia", uf: "SP" },
  { nome: "Paulo de Faria", uf: "SP" },
  { nome: "Pederneiras", uf: "SP" },
  { nome: "Pedra Bela", uf: "SP" },
  { nome: "Pedranópolis", uf: "SP" },
  { nome: "Pedregulho", uf: "SP" },
  { nome: "Pedreira", uf: "SP" },
  { nome: "Pedrinhas Paulista", uf: "SP" },
  { nome: "Pedro de Toledo", uf: "SP" },
  { nome: "Penápolis", uf: "SP" },
  { nome: "Pereira Barreto", uf: "SP" },
  { nome: "Pereiras", uf: "SP" },
  { nome: "Peruíbe", uf: "SP" },
  { nome: "Piacatu", uf: "SP" },
  { nome: "Piedade", uf: "SP" },
  { nome: "Pilar do Sul", uf: "SP" },
  { nome: "Pindamonhangaba", uf: "SP" },
  { nome: "Pindorama", uf: "SP" },
  { nome: "Pinhalzinho", uf: "SP" },
  { nome: "Piquerobi", uf: "SP" },
  { nome: "Piquete", uf: "SP" },
  { nome: "Piracaia", uf: "SP" },
  { nome: "Piracicaba", uf: "SP" },
  { nome: "Piraju", uf: "SP" },
  { nome: "Pirajuí", uf: "SP" },
  { nome: "Pirangi", uf: "SP" },
  { nome: "Pirapora do Bom Jesus", uf: "SP" },
  { nome: "Pirapozinho", uf: "SP" },
  { nome: "Pirassununga", uf: "SP" },
  { nome: "Piratininga", uf: "SP" },
  { nome: "Pitangueiras", uf: "SP" },
  { nome: "Planalto", uf: "SP" },
  { nome: "Platina", uf: "SP" },
  { nome: "Poá", uf: "SP" },
  { nome: "Poloni", uf: "SP" },
  { nome: "Pompéia", uf: "SP" },
  { nome: "Pongaí", uf: "SP" },
  { nome: "Pontal", uf: "SP" },
  { nome: "Pontalinda", uf: "SP" },
  { nome: "Pontes Gestal", uf: "SP" },
  { nome: "Populina", uf: "SP" },
  { nome: "Porangaba", uf: "SP" },
  { nome: "Porto Feliz", uf: "SP" },
  { nome: "Porto Ferreira", uf: "SP" },
  { nome: "Potim", uf: "SP" },
  { nome: "Potirendaba", uf: "SP" },
  { nome: "Pracinha", uf: "SP" },
  { nome: "Pradópolis", uf: "SP" },
  { nome: "Praia Grande", uf: "SP" },
  { nome: "Pratânia", uf: "SP" },
  { nome: "Presidente Alves", uf: "SP" },
  { nome: "Presidente Bernardes", uf: "SP" },
  { nome: "Presidente Epitácio", uf: "SP" },
  { nome: "Presidente Prudente", uf: "SP" },
  { nome: "Presidente Venceslau", uf: "SP" },
  { nome: "Promissão", uf: "SP" },
  { nome: "Quadra", uf: "SP" },
  { nome: "Quatá", uf: "SP" },
  { nome: "Queiroz", uf: "SP" },
  { nome: "Queluz", uf: "SP" },
  { nome: "Quintana", uf: "SP" },
  { nome: "Rafard", uf: "SP" },
  { nome: "Rancharia", uf: "SP" },
  { nome: "Redenção da Serra", uf: "SP" },
  { nome: "Regente Feijó", uf: "SP" },
  { nome: "Reginópolis", uf: "SP" },
  { nome: "Registro", uf: "SP" },
  { nome: "Restinga", uf: "SP" },
  { nome: "Ribeira", uf: "SP" },
  { nome: "Ribeirão Bonito", uf: "SP" },
  { nome: "Ribeirão Branco", uf: "SP" },
  { nome: "Ribeirão Corrente", uf: "SP" },
  { nome: "Ribeirão do Sul", uf: "SP" },
  { nome: "Ribeirão dos Índios", uf: "SP" },
  { nome: "Ribeirão Grande", uf: "SP" },
  { nome: "Ribeirão Pires", uf: "SP" },
  { nome: "Ribeirão Preto", uf: "SP" },
  { nome: "Riversul", uf: "SP" },
  { nome: "Rifaina", uf: "SP" },
  { nome: "Rincão", uf: "SP" },
  { nome: "Rinópolis", uf: "SP" },
  { nome: "Rio Claro", uf: "SP" },
  { nome: "Rio das Pedras", uf: "SP" },
  { nome: "Rio Grande da Serra", uf: "SP" },
  { nome: "Riolândia", uf: "SP" },
  { nome: "Rosana", uf: "SP" },
  { nome: "Roseira", uf: "SP" },
  { nome: "Rubiácea", uf: "SP" },
  { nome: "Rubinéia", uf: "SP" },
  { nome: "Sabino", uf: "SP" },
  { nome: "Sagres", uf: "SP" },
  { nome: "Sales", uf: "SP" },
  { nome: "Sales Oliveira", uf: "SP" },
  { nome: "Salesópolis", uf: "SP" },
  { nome: "Salmourão", uf: "SP" },
  { nome: "Saltinho", uf: "SP" },
  { nome: "Salto", uf: "SP" },
  { nome: "Salto de Pirapora", uf: "SP" },
  { nome: "Salto Grande", uf: "SP" },
  { nome: "Sandovalina", uf: "SP" },
  { nome: "Santa Adélia", uf: "SP" },
  { nome: "Santa Albertina", uf: "SP" },
  { nome: "Santa Bárbara d'Oeste", uf: "SP" },
  { nome: "Santa Branca", uf: "SP" },
  { nome: "Santa Clara d'Oeste", uf: "SP" },
  { nome: "Santa Cruz da Conceição", uf: "SP" },
  { nome: "Santa Cruz da Esperança", uf: "SP" },
  { nome: "Santa Cruz das Palmeiras", uf: "SP" },
  { nome: "Santa Cruz do Rio Pardo", uf: "SP" },
  { nome: "Santa Ernestina", uf: "SP" },
  { nome: "Santa Fé do Sul", uf: "SP" },
  { nome: "Santa Gertrudes", uf: "SP" },
  { nome: "Santa Isabel", uf: "SP" },
  { nome: "Santa Lúcia", uf: "SP" },
  { nome: "Santa Maria da Serra", uf: "SP" },
  { nome: "Santa Mercedes", uf: "SP" },
  { nome: "Santana da Ponte Pensa", uf: "SP" },
  { nome: "Santana de Parnaíba", uf: "SP" },
  { nome: "Santa Rita d'Oeste", uf: "SP" },
  { nome: "Santa Rita do Passa Quatro", uf: "SP" },
  { nome: "Santa Rosa de Viterbo", uf: "SP" },
  { nome: "Santa Salete", uf: "SP" },
  { nome: "Santo Anastácio", uf: "SP" },
  { nome: "Santo André", uf: "SP" },
  { nome: "Santo Antônio da Alegria", uf: "SP" },
  { nome: "Santo Antônio de Posse", uf: "SP" },
  { nome: "Santo Antônio do Aracanguá", uf: "SP" },
  { nome: "Santo Antônio do Jardim", uf: "SP" },
  { nome: "Santo Antônio do Pinhal", uf: "SP" },
  { nome: "Santo Expedito", uf: "SP" },
  { nome: "Santópolis do Aguapeí", uf: "SP" },
  { nome: "Santos", uf: "SP" },
  { nome: "São Bento do Sapucaí", uf: "SP" },
  { nome: "São Bernardo do Campo", uf: "SP" },
  { nome: "São Caetano do Sul", uf: "SP" },
  { nome: "São Carlos", uf: "SP" },
  { nome: "São Francisco", uf: "SP" },
  { nome: "São João da Boa Vista", uf: "SP" },
  { nome: "São João das Duas Pontes", uf: "SP" },
  { nome: "São João de Iracema", uf: "SP" },
  { nome: "São João do Pau d'Alho", uf: "SP" },
  { nome: "São Joaquim da Barra", uf: "SP" },
  { nome: "São José da Bela Vista", uf: "SP" },
  { nome: "São José do Barreiro", uf: "SP" },
  { nome: "São José do Rio Pardo", uf: "SP" },
  { nome: "São José do Rio Preto", uf: "SP" },
  { nome: "São José dos Campos", uf: "SP" },
  { nome: "São Lourenço da Serra", uf: "SP" },
  { nome: "São Luiz do Paraitinga", uf: "SP" },
  { nome: "São Manuel", uf: "SP" },
  { nome: "São Miguel Arcanjo", uf: "SP" },
  { nome: "São Paulo", uf: "SP" },
  { nome: "São Pedro", uf: "SP" },
  { nome: "São Pedro do Turvo", uf: "SP" },
  { nome: "São Roque", uf: "SP" },
  { nome: "São Sebastião", uf: "SP" },
  { nome: "São Sebastião da Grama", uf: "SP" },
  { nome: "São Simão", uf: "SP" },
  { nome: "São Vicente", uf: "SP" },
  { nome: "Sarapuí", uf: "SP" },
  { nome: "Sarutaiá", uf: "SP" },
  { nome: "Sebastianópolis do Sul", uf: "SP" },
  { nome: "Serra Azul", uf: "SP" },
  { nome: "Serrana", uf: "SP" },
  { nome: "Serra Negra", uf: "SP" },
  { nome: "Sertãozinho", uf: "SP" },
  { nome: "Sete Barras", uf: "SP" },
  { nome: "Severínia", uf: "SP" },
  { nome: "Silveiras", uf: "SP" },
  { nome: "Socorro", uf: "SP" },
  { nome: "Sorocaba", uf: "SP" },
  { nome: "Sud Mennucci", uf: "SP" },
  { nome: "Sumaré", uf: "SP" },
  { nome: "Suzano", uf: "SP" },
  { nome: "Suzanápolis", uf: "SP" },
  { nome: "Tabapuã", uf: "SP" },
  { nome: "Tabatinga", uf: "SP" },
  { nome: "Taboão da Serra", uf: "SP" },
  { nome: "Taciba", uf: "SP" },
  { nome: "Taguaí", uf: "SP" },
  { nome: "Taiaçu", uf: "SP" },
  { nome: "Taiúva", uf: "SP" },
  { nome: "Tambaú", uf: "SP" },
  { nome: "Tanabi", uf: "SP" },
  { nome: "Tapiraí", uf: "SP" },
  { nome: "Tapiratiba", uf: "SP" },
  { nome: "Taquaral", uf: "SP" },
  { nome: "Taquaritinga", uf: "SP" },
  { nome: "Taquarituba", uf: "SP" },
  { nome: "Taquarivaí", uf: "SP" },
  { nome: "Tarabai", uf: "SP" },
  { nome: "Tarumã", uf: "SP" },
  { nome: "Tatuí", uf: "SP" },
  { nome: "Taubaté", uf: "SP" },
  { nome: "Tejupá", uf: "SP" },
  { nome: "Teodoro Sampaio", uf: "SP" },
  { nome: "Terra Roxa", uf: "SP" },
  { nome: "Tietê", uf: "SP" },
  { nome: "Timburi", uf: "SP" },
  { nome: "Torre de Pedra", uf: "SP" },
  { nome: "Torrinha", uf: "SP" },
  { nome: "Trabiju", uf: "SP" },
  { nome: "Tremembé", uf: "SP" },
  { nome: "Três Fronteiras", uf: "SP" },
  { nome: "Tuiuti", uf: "SP" },
  { nome: "Tupã", uf: "SP" },
  { nome: "Tupi Paulista", uf: "SP" },
  { nome: "Turiúba", uf: "SP" },
  { nome: "Turmalina", uf: "SP" },
  { nome: "Ubarana", uf: "SP" },
  { nome: "Ubatuba", uf: "SP" },
  { nome: "Ubirajara", uf: "SP" },
  { nome: "Uchoa", uf: "SP" },
  { nome: "União Paulista", uf: "SP" },
  { nome: "Urânia", uf: "SP" },
  { nome: "Uru", uf: "SP" },
  { nome: "Urupês", uf: "SP" },
  { nome: "Valentim Gentil", uf: "SP" },
  { nome: "Valinhos", uf: "SP" },
  { nome: "Valparaíso", uf: "SP" },
  { nome: "Vargem", uf: "SP" },
  { nome: "Vargem Grande do Sul", uf: "SP" },
  { nome: "Vargem Grande Paulista", uf: "SP" },
  { nome: "Várzea Paulista", uf: "SP" },
  { nome: "Vera Cruz", uf: "SP" },
  { nome: "Vinhedo", uf: "SP" },
  { nome: "Viradouro", uf: "SP" },
  { nome: "Vista Alegre do Alto", uf: "SP" },
  { nome: "Vitória Brasil", uf: "SP" },
  { nome: "Votorantim", uf: "SP" },
  { nome: "Votuporanga", uf: "SP" },
  { nome: "Zacarias", uf: "SP" },
  { nome: "Chavantes", uf: "SP" },
  { nome: "Estiva Gerbi", uf: "SP" },
];

export default CIDADES_BRASIL;